# Site Settings
title: Ömürden Cengiz
url: 'https://omurden.com'
baseurl: ''
description: "QA Engineer & DJ based in Amsterdam"
theme_skin: minimal

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
